### ISSUE TITLE
Queue acting incorrectly

### ISSUE THREAD

**Issue by iammaxc** [rickyschoolsFS/ListManagement#107]
With single list in queue, program infinitely loops and attempts to rerun list.

With multiple lists, program infinitely loops the first list in the queue and does not progress to the others, while still moving the lists out of the queue.

**Comment by rickyschoolsFS** [comment]
The issue is that the program experienced a problem in the finra_helper module. I think that there isn't adequate processing in place to remove data from the queue if the list encounters an error. 

attempting to address this now. the error can be found in the log file for 5/31/2017.
