### ISSUE TITLE
List object not being updated properly when list processing gets completed.

### ISSUE THREAD

**Issue by rickyschoolsFS** [rickyschoolsFS/ListManagement#109]
It looks like the list object id on emails that come from Salesforce are being parsed in a way that's cutting off the first few characters of the id (specifically the first 2 characters).

this is problematic because it leaves lists in the queue for an unrealistic period of time though they've already been processed. Would you be able to fix? 

example:
ListObjId: _10L0000008vRfQAI_ should be _a310L0000008vRfQAI_ 

I think that the code that needs to be augmented can be found in the utility/email_reader.py file, within the 'iterative_processing' method on line 149

let me know if you need help.

**Comment by iammaxc** [comment]
Changed window of string

**Comment by iammaxc** [comment]
![image](https://user-images.githubusercontent.com/19572030/26900728-298e4dac-4ba1-11e7-807d-456208cc7398.png)

**Comment by rickyschoolsFS** [comment]
thanks. could you please submit a pull request for the code so that we can merge it with the main branch? after the merge request, we can close this issue.
