### ISSUE TITLE
Move Old Files

### ISSUE THREAD

**Issue by iammaxc** [rickyschoolsFS/ListManagement#134]
Need to migrate files (especially for account objects) in which we may receive multiple lists associated with the same object.

refer to logger self-maintenance

**Comment by rickyschoolsFS** [comment]
fyi - maybe these will help:

**StackOverflow:**

- https://stackoverflow.com/questions/15034151/copy-directory-contents-into-a-directory-with-python
- https://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth

**Python3 Documentation for Distutils.dir_util.copy_tree**

- https://docs.python.org/3/distutils/apiref.html#distutils.dir_util.copy_tree
