### ISSUE TITLE
sqlQuery: Only 170k out of 205k advisors showing on the daily csv file

### ISSUE THREAD

**Issue by rickyschoolsFS** [rickyschoolsFS/ListManagement#52]
It looks like there was some issue this morning when this process ran as the csv file only shows 170,000 of the 205,000 advisors in our database.

Might be a good idea to check it out prior to running any lists today.

**Comment by iammaxc** [comment]
File looks good now. I didn't change anything, but it usually takes some time to build up so maybe that was it?

**Comment by rickyschoolsFS** [comment]
If you feel comfortable with the code, then let’s close the issue. If not, we can wait until a few days to dig deeper


Ricky Schools
(407) 803-5922
