### ISSUE TITLE
Not sure if BizDev members being added

### ISSUE THREAD

**Issue by iammaxc** [rickyschoolsFS/ListManagement#73]
out of the 3 BizDev lists ran this week, all returned "Attempting to insert 0 in the BizDev Group."

Not sure if issue with process or if indeed all members are already in the group (aka no new members)

will connect with KB.

**Comment by rickyschoolsFS** [comment]
add an attachment for advisors currently in bdg

to remove is not being sent along

**Comment by rickyschoolsFS** [comment]
addressed in the recent the below commit:

[https://github.com/rickyschoolsFS/ListManagement/commit/8a329b0c23e8326def3cee343cd91f7198f29513](url)
